export const EMERGENCY_STRINGS = {
  en: {
    emergencyNumbers: "Emergency Numbers",
    call911: "Call 911 for Emergencies Only",
    nonEmergency: "Police (Non-Emergency)",
    fireRoutine: "Fire (Routine)",
    cityHall: "City Hall / Admin",
    publicWorks: "Public Works",
    sheriffsOffice: "Sheriff's Office",
    poison: "Poison Control:",
    crimeStoppers: "Crime Stoppers (Cookeville):",
    gasLeaks: "Gas Leaks (Cookeville):",
    waterSewer: "Water / Sewer Issues (Cookeville):",
    serviceSupport: "Service / Support Area",
    phoneNumber: "Phone Number",
    availability: "Availability",
    suicideCrisis: "Suicide & Crisis Lifeline",
    poisonControlCenter: "Poison Control Center",
    domesticViolence: "Domestic Violence Hotline",
    humanTrafficking: "National Human Trafficking Hotline",
    veteransCrisis: "Veterans Crisis Line",
    substanceAbuse: "Substance Abuse (SAMHSA Helpline)",
    childhelp: "Childhelp National Abuse Hotline",
    elderAbuse: "Elder Abuse Hotline",
    runawaySafeline: "Runaway Safeline / Youth Crisis Line",
    avail247CallText: "24/7 call or text",
    avail247FreeConf: "24/7 free & confidential",
    avail247AnonHelp: "24/7 anonymous help",
    availTextHelp: 'Text "HELP" to 233733',
    availVetsFamilies: "24/7 for Veterans & families",
    availConfSupport: "24/7 confidential support",
    availChildrenAdults: "Support for children and adults",
    availReferralsGuidance: "Referrals & guidance",
    avail247Teens: "24/7 for teens",
    localEmergencyNumbers: "Local emergency and non-emergency contact numbers by city",
    nationalSupportHotlines: "National Support Hotlines and availability",
    utilitiesAndHelp: "Utilities and Help"
  },
  es: {
    emergencyNumbers: "Números de Emergencia",
    call911: "Llame al 911 solo para emergencias",
    nonEmergency: "Policía (No Emergencia)",
    fireRoutine: "Bomberos (Rutina)",
    cityHall: "Ayuntamiento / Administración",
    publicWorks: "Obras Públicas",
    sheriffsOffice: "Oficina del Sheriff",
    poison: "Control de Envenenamientos:",
    crimeStoppers: "Crime Stoppers (Cookeville):",
    gasLeaks: "Fugas de Gas (Cookeville):",
    waterSewer: "Problemas de Agua / Alcantarillado (Cookeville):",
    serviceSupport: "Área de Servicio / Apoyo",
    phoneNumber: "Número de Teléfono",
    availability: "Disponibilidad",
    suicideCrisis: "Línea de Prevención del Suicidio y Crisis",
    poisonControlCenter: "Centro de Control de Envenenamientos",
    domesticViolence: "Línea de Ayuda contra la Violencia Doméstica",
    humanTrafficking: "Línea Nacional contra la Trata de Personas",
    veteransCrisis: "Línea de Crisis para Veteranos",
    substanceAbuse: "Abuso de Sustancias (Línea SAMHSA)",
    childhelp: "Línea Nacional Childhelp contra el Abuso",
    elderAbuse: "Línea de Ayuda por Abuso a Personas Mayores",
    runawaySafeline: "Línea para Jóvenes en Crisis / Fuga",
    avail247CallText: "24/7 llamada o texto",
    avail247FreeConf: "24/7 gratis y confidencial",
    avail247AnonHelp: "24/7 ayuda anónima",
    availTextHelp: 'Envíe "HELP" al 233733',
    availVetsFamilies: "24/7 para veteranos y familias",
    availConfSupport: "24/7 apoyo confidencial",
    availChildrenAdults: "Apoyo para niños y adultos",
    availReferralsGuidance: "Referencias y orientación",
    avail247Teens: "24/7 para adolescentes",
    localEmergencyNumbers: "Números de contacto de emergencia y no emergencia por ciudad",
    nationalSupportHotlines: "Números de líneas de apoyo nacional y disponibilidad",
    utilitiesAndHelp: "Servicios Públicos y Ayuda"
  },
} as const;